# ingress:
#   enabled: true
#   labels:
#     components.nora/tls: enabled
#   annotations:
#     kubernetes.io/ingress.class: traefik
#   hosts:
#     - host: uptime.nora
#       paths: 
#         - path: /
#           pathType: ImplementationSpecific

volume:
  storageClassName: longhorn