---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-credentials
  namespace: github-actions-runners-myzopotamia
spec:
  encryptedData:
    .dockerconfigjson: AgCXkSUTauIqRGX611bse2yPK53rXRSYIXoA9drOURjhYm/HvHXapDhBj9QArPAycRFdDgSAzK3KW3oOK3ICMlcKGA4CDxguYH6ZocnlEi5bkvPV7kgdc6UiMyWCBjWaTfch92+gv5CJqs/7n7B6CZMWRtXTu0t6ncNFnkH9mOYDqzA+pQjJ3EVWGxlo/YzOVgDZ6sMd4sS0fkJaqWfkxyU1o4HDYIRKdDLxYQ95RlwnzIXldyJ/nAYhIj/hdEWNp3etmVZ+bay+2/kRHg3DuVZa9+sbky6CSmHliO7f6TbgY6j3n0BNFqAtdTap6ztJ9mUwZuMu4LBVc8CSYjqlYGjbnxBFeQO03kjGCLlZlzovAkfsewt8xKYvgR5qyTEO88h+vuDEAnCpl2mtPasUxY/YcZtuS8Git/Yu6Xs05YGPoeLiyMUMIImMWb+b2nC5CC7RuWlcqoQjVk2PKmsY1VDIgvxmeDGWfdZyVA/7tWrUqqFTmx4L/hamSOpMLavFLoUsBmBO+5kJ8uGrJhHeyETe8abHMB7OpVzARA6PzusBAMcNQQLyQGhCwMk5y+n07VW4K8f6BtdYQr6W0COERtlYH7SOgZxB+AJ04PbEqFAr4ZVoLX7guAS8k7Vj7V4iT3pP2xymkPOEWdUtF+dZ6cys2KIWafsob6VllKTImQM3ZQ32VVDgkglapf3lGU2m2sD9QaIgygGEFw3srb7Iqlc+PNDIN4/tD2MdAXlf2kpgzDLG3pVX4PXeOr82Zq/uYwy4JUN6YXGwXzo2dmfHtlbQqA+095YtUw2Ch0z2PmvAHvzq9GSrUFcrmHtupicheWPuVuD4n38IU+Z4F4pBfzI3O/eYAwfC0DPf6wQ5Y03Hp5qXko+0X4lIe9OYFQ==
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-credentials
      namespace: github-actions-runners-myzopotamia
    type: kubernetes.io/dockerconfigjson
