---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-credentials
  namespace: ether-docs
spec:
  encryptedData:
    .dockerconfigjson: AgAO79dDtlf4jIqLwMfqJthZKZY/Yun+6uS40S1HYWjPcRB3x4dU/8W/rDM1/cjRyP5HKHbOLtmFyAzj7U24QTFSS/XCJ8O/wVJnRanr77CgDVweJUOOEq6TkQRW+viAy3y+UOgmopBhsv7oKpqyXepnInfh1ifIme6YK4RPaxuJ9Iis/lNgmNte//qd+lMY8XjRQ47jF26FVCX8gihIeJMb6wEw48iSvzNeQUzw32LhWOmciVAFTbvWMy2r/qWBCfiAi6EV9eYZECwU9vVHCSXMZ8iEiEqVVH/QbPPL0zgOEOaIr+Q5yVl6xLq5Ra6KjQvObqu/1ecEIUCUkEbAFMuWomy3SUjsEDS5rcxUWpcdUuLzTYdVAkHqXTVFE80xcVh8cHjks4qO7eQjzIeZpe06xZbPLQ37cZ0eWEyj6j+aGWSpcw6+bJ5leYYMmRCiwxxAq+6X6bIuhJONDsIy8LtfwPHc6KMNHdDZYzKsQkjU7uY1DKOpYhcBo0jvTQkJGG8edD1onrzUBgxKdSuqlAxM0ey0TvuJcoABXr+yh1MC2gSEsFwF+PuFdQcxkc2cnd2fcNRUQqwInVvuw2LE9ThbYHQ5li6IqsAtVP2rspIrLVlU7rQBONmSGRIKQDzXNGJFuUXQL6KXLufw46CIjLrfDmUR2stBbpSAHId9BHy1YYG9yexz/SmJJmTJ+/JZITpnpZReT+FVahCUxL4GeK18xKl3N+ZhzfgZN7l9BVfLjKNY2iRlZix2wOinutzv7TFnGkc98cMIwz+NvNLhIws+CddYN9L+FT9lDxlkEVhD+dLsGiQ2/fT1kwdcz24GXflQujcqBevFaNdWtYyQ0WyIb9ry8yfaEIUWoVPSe32PojTIH8nFqvt4rxs3ZA==
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-credentials
      namespace: ether-docs
    type: kubernetes.io/dockerconfigjson
