---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-credentials
  namespace: github-actions-runners-edgar
spec:
  encryptedData:
    .dockerconfigjson: AgBIAbua9PgYtTDcIAAKVgJqWMoNuUcd2AaTWFwi0x8iJtRD7y7xtjzirfdoFhz2VBS4bFigxdio6LVyYRT/mJgFbxJp0C7qhaD7+D7zCCClg9kWUCgek7eZcuP3/Qw1pfO3k9DCuQLy8EArUgz8vXFdo7BNc7BwEyuJ/kHK9oomNUBIIv6lcVaAZXZz3O9IQJDrahMenS2N2cn5eUsVQsh7H5iLPmW9yf/JmNPO2XqhlTkagqfjOe2mThVvM7l9VEkGod3IXaBnATYXJnEbx+jttHa9BaChzsgw9Z1Ne2gppAwhTxh5vszW2g8GvAfsOTLrcJCYyd/rZbs0QWUqN/DabyCmxR2ulgVl7DiPuv+2O/MlI90aVU4SqwtwOs72jZpw/kaa9pH0XJCodtVTohTtvghVstWejRmVT6WVshz7KqXZlv4SMg1GEkUazwRG+y7jsw6jWo/Oxdo2Vq/Gsoxs6BAR2B2kuWzXpLRxEXxwgWAD8/hRfA+1aLvNj4xY0MrnI+xgPHTeu0P9ZTrhR4VpDcoYF5l5IVbKSyL5ZTubkKHeFod1x2xilI0JS3ogmViwA1oM2m+PA9u5Xtw43hPzYxYSpBxMTQh39SNqqZ5OvyuF34s23FRRGvkK1Qbm2JpxPpO57t1L8y6ldMNMoRRfCqu5OdqK+Y3mjbLGS4mxttYJ58nHsvINTNb0yvrWbyF4DWGCQqrCWPMjF2sAz76pIpJoS5aKQGxEKA/WDZXe7ocd3sT93M9XLZOrrK3op2cd+HASUcJI+eaZ7qx3ssSA12QlqEnlkc6TVk6ERBlQUT8JuXX3McXRH9Nt2g1bqhqwyAHfVM3AD9cNcj9YmCOBR1caGIfm9tGSqNaTVIq3lmsICztwQCGaD5XSSrj+Cv1ugZOXliSV
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-credentials
      namespace: github-actions-runners-edgar
    type: kubernetes.io/dockerconfigjson
