helmCharts:
  - name: gha-runner-scale-set
    repo: "oci://ghcr.io/actions/actions-runner-controller-charts"
    releaseName: ether-runner-edgar
    namespace: github-actions-runners-edgar
    version: 0.11.0
    valuesFile: values.yaml

resources:
  - secret-pat.sealed.yaml
  - dockerconfig-secret.sealed.yaml
  - longhorn-pvc.yaml
  - cicd-patching.yaml