helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    releaseName: tailscale
    namespace: tailscale
    version: 1.88.2
    # valuesFile: values.yaml

resources:
  - oauth-secret.sealed.yaml