# How to use: add an empty envFrom if it doesn't exist yet and add a ntfy-token=enabled label

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - auth-token-secret.sealed.yaml

patches:
  - target:
      group: batch
      version: v1
      kind: Job
      labelSelector: ntfy-token=enabled
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom/-
        value:
          secretRef:
            name: ntfy-auth

  - target:
      group: batch
      version: v1
      kind: CronJob
      labelSelector: ntfy-token=enabled
    patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/envFrom/-
        value:
          secretRef:
            name: ntfy-auth
