apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - auth-token-secret.sealed.yaml

patches:
  - target:
      group: batch
      version: v1
      kind: Job
    patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata: {}
      spec:
        template:
          spec:
            containers:
              - envFrom:
                  - secretRef:
                      name: ntfy-auth

  - target:
      group: batch
      version: v1
      kind: CronJob
    patch: |-
      apiVersion: batch/v1
      kind: CronJob
      metadata: {}
      spec:
        jobTemplate:
          spec:
            template:
              spec:
                containers:
                  - envFrom:
                      - secretRef:
                          name: ntfy-auth
