---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-credentials
  namespace: edgar
spec:
  encryptedData:
    .dockerconfigjson: AgBrhA/2gbzQtQitpW9e2B3nbvNSNdDqm5460JSkXWTQOU0M4vdCGuAdK+bE6rToBj8gmEmS2MAoBRGOvh6mlcZv0dmxMGHELer93aI3ZcfVy8toc9RX6FFk9hcQpzd32pBxRswNx8hSTHgxb8qxFeYFNkydubdoGBI2aygN+Er/7NIR0SHPf9JGicXKLmVu8fsFAT/YtfS5jtby46v18S11LBw/A7DxA/waBiOxMtUvSI1VKaE0VTCWxfQGWwzGbIZ5PG/Z1AO2BM0F9eULMX4v0XHzsWMUFRzRI7krC6o/icUqjxcWfq3N21VL+v2E3ZwUvhMFj6N4qCn9K5Q4xnFvOSXK9ChPZqBu0wiQWlAp5JQ8MeZlZIfALS7+GxTAgkcpWyoOWL0GD9WfDluGLQxKFiBJTaNZ5k9H/Bt9BeZhndQS+TCqDueTPSbByiZs2inZIv1RtAekS+1CNI1uhPmikYrvvm7ygf/7/KxCzrYyZS0eWkii2Uks+dgmmQkxauSuwh+61mxSlpzRYRlbLJPOy35JJ4Ya5p+52O3fsxuzZEkSNuPJrTiPs5hjk7flPBmzRKu4gu3JaaEnaUiVzZjLwq7qIDlFGN4SCIqicxTV11FQ/gPYwoLn1gT0povGMQL7Z6cAcyaQYGi1kVpwGPDIsayx/9qnAy4BvUmCbzlokJowGOau6SNQSCcMk6zQsJQ5vtPBxKLwJXR3UMJebz1CWT63HYYP+Q3KXQmL/m+0cFzxAe3CT17b9xI0Y6IUE3sItIq8pKKKXXdI6tZSuHDS4QLFpt0bNj93tjIM9p3Qpwj5XCwgInGcBeLB28Lu5roR+zWemCBmEVi5HcySfN8qKOYmbXd7BPr3RIfcCSa1EBKdPAwLfmfJWTWYNbufy0pswI9HGhvW
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-credentials
      namespace: edgar
    type: kubernetes.io/dockerconfigjson
