---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-credentials
  namespace: github-actions-runners-acolyte
spec:
  encryptedData:
    .dockerconfigjson: AgAsL/VzsHEhHuRVy+fM1Ije7VAUa1dMKFMGlQTHhdQUtXtt/JpyW7UP9G6PNAQnLg/gO5XfKUxSVlgsJSDMePhZM/7xiQ4O9qN3mT8A0tCWAJOFgkBZQv0eE43dWb00OTCCIxtJmKD19nYrD1DjDqcXX5TI2LNVHI4dO/bE7O7zZPfN+MheO5PxuT21vKlvZwG8AQeBQ7KpWfmvUix09P781bFOHfBTMxr3sBqKQ8JDyDyFdu7p8F+07pgIz6lnGqHQaIeWifNZll7WNq5VY7daL2NizTSSSCfIp7okLIdiZXZT9ICle0+FlK5lxFPm85fn3yM0e/e4c+W7+D0aMpFZL9IQrevbXv1RD3udSJJA7eSRibcSAx1BTC9kPQiH0gOIQ295BRCsVT/TPh0492lFy/rahHjQcUZlmy09TEdH004M2GTCL2b+jEaP7gCSvOJPRbxwMUcGGfzHXBLSTDemPH0COtXwuHIr52Ae2aQo232ONRH+Tfcc0/gSZqXXxxLmC9woddP0JLo6HJFI62zcaO6MP4Ox/pHph8YjyOln7CLGtEsF/51Ubg1rEFlz6+wiD5LOcB4NymiQW9xLwkJ+RnwSCuDiWvKKwFJKeXmBKYSpdS5dy5aJ9uWmJnUT8KamGKSet5Q5Ji1pl9tW9bxlNmTGZ44XpumXuYf/jwjW1x9iRz2I/+wfoO+ycUae1BusfhxvDiwqa6JQZK7C5ctITAN0dWrFE/nsjEuDQac8cCDy0B5gdrCqMAsdDhJVEK1LtLELeQC+I2i5kSvdxWat3tA052TCMnrhpg/t7vrCzbxo7dMg/XLSLIzd/ClHavI9eXi5mvJLksBI40PPyIExdO4vYPgPPTjtg1/km1nYQ9skGQXXiaw2GatYSQ==
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-credentials
      namespace: github-actions-runners-acolyte
    type: kubernetes.io/dockerconfigjson
