apiVersion: apps/v1
kind: Deployment
metadata:
  name: myzopotamia-blog
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myzopotamia-blog
  template:
    metadata:
      labels:
        app: myzopotamia-blog
    spec:
      containers:
        - name: myzopotamia-blog
          image: registry.gitlab.com/myzreal/ether/blog:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      imagePullSecrets:
        - name: dockerhub-credentials
      volumes:
        - name: nginx-config-volume
          configMap:
            name: myzopotamia-blog-config