---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-credentials
  namespace: blog
spec:
  encryptedData:
    .dockerconfigjson: AgCC4wp8aIGoT1Bj62QUNRiNFoQ+qLmwuhaNbMBeFYu5OYatlpGKl/6RUGpfLniJBJx41hteAP+GWUTxlx2VjtG2/r61twJX3mOsIBJIEQ51Rc2q1WE8s1YEuUv59C7NNA0OwZdXfjHbl4ay8/cOjkB7VTzRilRwTYyGFHM4SFP91TGtCNch45M6/dBMD7ElIWwXxFyFIK6rawLWLDK86xyxC6Wv7tJkysX2ezFF8VMNDXc03zvtcZVxCT4Qv+rrfo6N0nKKb1zzKsSWRusv9xzcNsQMT2hRchwZXKuYfyLIEXhXpCrK/Ry3pZr4NAAnAyhceEWDGO7sh0wTSpnvtj0bvlXRf//F4CsC5B4vlgLcA63qgYZBJPi8RzP95zEY30/xFG0rkcyfa+0Na85tqW0C6HVSoOe615XLnnJDJXxXamQxZ0WsSz2cX6tNVz1GFufJ5KDX5ltnClUQXC7kfCN3Bz60Z2iQ0zAs4hllOWvboJuXBPI3JEveOZRY72gYgFE5b7QneM3hO0+P1c3FZu92mBRPFh55Wf0R7ZNREGZv8mBvIROCq8jv81+ldSSHFo2LNomrM8UGpiKvIt33zHmsTTnctpE8lc6uMW1zEUMtgWdQi830b1BgUS5nd54iFNvGKEHukUXod/U1Mzg9ILXMga/PQgaWZMkLQjkr1XuCeufCPpZmt0VOWdF/EoQDMxamXleO5zcPSUZZOGBjrHBgiAkLgt0VAE34S5ORstaUNzPLg4hDRl9T0Ym05NvtM4KN9kYqXJ68pfhGNTH5F0tURjL/nyE1ycTiwemz9Wi2ZrGpSgZhYYCpq5xw86GKU69qEKVYtqhyevJTtjtaaqyJ12348pgOnRzmzDhp+VFEJ/P02fVdmj0MCQL0GA==
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-credentials
      namespace: blog
    type: kubernetes.io/dockerconfigjson
