helmCharts:
  - name: gha-runner-scale-set-controller
    repo: "oci://ghcr.io/actions/actions-runner-controller-charts"
    releaseName: ether-arc-runner
    namespace: github-actions-controller
    version: 0.11.0
    includeCRDs: true
