---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-credentials
  namespace: acolyte
spec:
  encryptedData:
    .dockerconfigjson: AgAD76rvIETqmDX7TatI7ihkWqmlOwZ3TiA8DoYHaRT3vY6Wr8+zWfn37wmFzlz+sVlXlRDjKu8JNxWOZ1TWh2/4/Eoaj6CCpIs/1jk7Oc7nzQST9WlzRUgDnfc6e2WRRXwP27RxPfztYGB/Fk6IIGTlXdpRzmqcOeyDrOZ0lf7X4JBWs9XpzyS0NLB0Z2UWXy1GtN66ucRIhJro8SE9fnCDoC9un4M8kC1+yjfE9YQDgBHbfKQc7zYF0ymo6MGAof0LfwJ2RvIWXgD63mBQcMhyWPy6NeczvJRaPSuLH/mlqF9Xv9Ed6a3oKAO8P1xuFddn8v1723Ut1+eoOKnOwX79D4XnXlzBasDhdv76OIytTAT884pfz0LDpQsBsG3b9Wz746Rh3xwRKASgn9YFAgec2uv65mbFF0WeT3cD3l9Hqs2Ea0Hvjhq30OSrb12AdQfGM41Qq4NNdcY+RfOhsyh/lZJWhuHUfTQzz50zAPKFnMHdUGGsP83J7m/q4k3VscZO2upJtMqoQ2BN4MoBrn+DHoSpdm/E8KChMtX1RmF+fCbLZEfY4Pbqk0S3TKsFBmIVyCI7ryOeq8YL4nqZl3lmyNV0Bb4SL69tTe20+GSxTdFYGhQ1r9q2mF7hUKHEweL9CmARhQtPz8mzDWrBtIi+QGVs8LgP/FU16JvfNw2I9xIyjcZAMM2azglA4vVXjf0RBi8+GQtkx6ImhDjhyzNXsgflXcM2TeRfBSh0fR6sgv4dhAmE50kJ/BC2NhX/6YNtUfGR156+Y1z6dXRUh6+1HkTYS1vNEnpn0HyDpHToVtipC7qj5qvf3b5ubsWoI6e9/YEj733djMfl6jk5jJtlfCi0/ckg5weyzJtQyf1oH1plLZGTzEALDb5wbA==
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-credentials
      namespace: acolyte
    type: kubernetes.io/dockerconfigjson
