apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acolyte-ingress
  namespace: acolyte
  labels:
    components.nora/tls: enabled
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: acolyte.nora
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: acolyte
                port:
                  number: 80
