apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acolyte-ingress
  namespace: acolyte
  labels:
    components.nora/tls: enabled
  annotations:
    tls-host: acolyte.nora
    kubernetes.io/ingress.class: "traefik"
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  # tls:
  #   - secretName: acolyte-nora-tls
  #     hosts:
  #       - acolyte.nora
  rules:
    - host: acolyte.nora
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: acolyte
                port:
                  number: 80
