namespace: acolyte

components:
  - ../../components/tls-ingress

resources:
  - dockerconfig-secret.sealed.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: tls-config
    literals:
      - host=acolyte.nora
      - service=acolyte
      - port=http
      - pathType=Prefix
      