apiVersion: v1
kind: Service
metadata:
  name: acolyte
  namespace: acolyte
  labels:
    app.kubernetes.io/name: acolyte
    app.kubernetes.io/instance: acolyte
spec:
  selector:
    app.kubernetes.io/name: acolyte
    app.kubernetes.io/instance: acolyte
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000