apiVersion: v1
kind: ConfigMap
metadata:
  name: finachy-config
data:
  SELF_HOSTED: "true"
  RAILS_FORCE_SSL: "false"
  RAILS_ASSUME_SSL: "false"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  REDIS_URL: "redis://redis:6379/1"
  OPENAI_ACCESS_TOKEN: ""
