apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 9292;
      server_name n8n.myzopotamia.dev;

      # Rewrite path
      location /rest/oauth2-credential/callback {
          proxy_pass http://127.0.0.1/rest/oauth2-credential/callback;
      }

      # Block ALL other access
      location / {
          return 403;
      }
    }
