---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-credentials
  namespace: github-actions-runners-ether
spec:
  encryptedData:
    .dockerconfigjson: AgAIWkrPV/GvvDEnkTYdeC1ENZzqUbNSrj6oMl2h2v6qa3GiGyWaKX8b+hAO2g5Fizb21rdnPRV/qCJ7RhqrslIDx5TTeK8BNsK11NVDUXMVDhdzk/07VWdv3a8i6iiQBYxVF/yM8/vEQlemAi28iv5QRcNbbNGu4dLozMhBqVqJwDcR9PVhC8gBvDO800foTik8vv4hnur9djYUGEVps+NXEgB1GDlbbGhQ19C64xFONyuXExHMQ7ckVoyEsehnoZo+c0WvUiyxF1LYApUJmXVEOmr4Q6VjcXm73Em0aadq0zDH3vCOApR93nYLVAEWrpDu6P7yXFE41AA/TIeEQJIJ5Od+Do5VW9WfaQCS1GFsiVQLJcjZzxxrZZOhKeo+QgiRNiT1KAx8Sg+GvI47YSaAo5VS3D0h8PVt04otOFLFePcUMaNMUqKD/gUaIwmNPpcDmK9g+d1lE1kTD6cfK02LonlbRV3m6JANMQTo0aD9Xmj5SxsTMfKqMOEln3XyCawOyQqT9eEyHBS9fpY4Uriwo4dUM2BJsCCEvZWMf6qNHQJCxqG6Uq+HbX0TU79nxx81bO2NOGv5B78n08WYk9wRRCJ5cu4dnwQW1m3ZyF6ewDSSuNLxAG3/5gYHzX3a7B78jSamHr0EBUg5nqmJopxvDYc380batvLbBfL02tBbVEHu3K9zej45PyPHccFrrYOIpQeB2Grgw1FYCOiP7VXFt/A/dcbBCK16Who4qXhwzL9pxpHqPetw2KyOiJGkGZa94eUTCdamrI35MVpdOC0iKPZztgVSG6ub1l8au3h7hUjIqtY1muvJ0WN+k2zamw0jSyaKjbquijF4BmspmYisuqFjX0RoD2/i3NuyxPTp4A2ty8zC/n97mrXCrQ==
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-credentials
      namespace: github-actions-runners-ether
    type: kubernetes.io/dockerconfigjson
