---
# This is a Sealed Secret by bitnami
# It was sealed locally with this command:
# kubeseal --controller-name sealed-secrets --controller-namespace sealed-secrets -f input.yaml -w output.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-custom-password
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDH/jc9Spm091+e86LYLeAEN80vNs0jqQC71150vZR0AkGCuqSXd5c3zYwFzHD4IgWObNni77IWJyn5hbg/4L9TLbiFoyiTPM8GE46TlQJsZMFC435zFp9tXeXgYiaeJ3tnch+790RtPrOdEra0PZN24uKcQpHNFuwC6q6Y4vL/AwAB4vHiQ9i+/Q8w4eiD9JH9rhKI1JA2F2z0Ul+xDfasyEXnmLoDk1IGvzscUfNGjq+4adnMKOSlikkoB+udZ12ZJvCT7BB2Dxva0He2weABVe/S7WrBg79iBgaNNNdRuLSv8DifVh1e7Xfhn46RXxDLUIyJWvQtvaDamMKEZct089KinjHZKtnDyv1qLeuGegkuPCijvgWOjZqIksAIgK9amUPloZcSWi//gp2rhMnhzxz2V5TJVGVuXeBNsPf5uVoIrqy5ndwQegT83feVL9QypLGTjAGMajBEgI9B1RZ+9xTLL/XUrBqgC2gR4zWWfart+kHonBoFuQ0uAS/5ERbwRJx/hdluQ4v4vQtlQS7tQmA2+VQ2OLnhjvJnYkCVsS/1S9XmVnZXAHFCoPYdwdDs9h8YL7eBqLAxGkqnSYKwnj7W644cMgwE4CL7TtM6BGGYlbOVrmhJRY03CkQNjpE3XSxKoQlmNF81j+I35rgmuprJB7YLazHelytuDeO40SJw8bCxZTTuiif7k/ORqK/BOuz6ByDNVQCcftYjGFr8
    admin-user: AgCEYgqRnR4Utb9GgRf70cqZGHd6698Dfpb/TM4gRAWLHlXQyuLPVLmJYeC+aDx0uQgidXTB9rxHjNpO4NaNt46jwkd/OIMKEz3NsNiAocz611PGKaEHNSEcl1nGCvCaxLc1FtrCO5+Rk2z3WeQvonb7AWRGn166CcJph9BWuC/2JXY12LYXyyR97z/1z8dciQ9n9uCQ0F08sjyfBw9wSsF4E0HW+wzwqM/Qf7T1f3PRA7sah+DXUnpKQnzKLbXfoJ0DBXsT19UdWRdjbIrBLDEBvCPAfeZeUt3FILNmZlDt1m3DAdDNeil6yDsAbn7iUSiHeBjWbVMS9LM34csblUu+DXj3kBwdcBF7pYRwB80C+BuEI/NFz6XTCoNf3sjXTdPgFnzYO2ZvjE/lPOOqqvOsfh5ekLTnzb2Vrm4rQ5UahohTeFLexlpgJSTU86r6BJCRn58poQx1kwzUbjuQ+K0d+RoOA66NOiQXddsoIIX/J76+f8K5HBXUaMKWCbyyZaoTCGM2f5isTSlCFPlGMnao2Rwnwg1q0hCIlZW6CUXS77QQ8hvkLjl/lvDoSe/vC+tmO0sUc3httCBfc/aEiYZuaoPSQwCoJiOC94AlJNTCr52s6np829AklZoXOXcUUUJfJQgYx1JSpxyJkTIcp/XZtDbF6dzfpngR1WUIP9s8Jf37oj63/8a91Z2XLYJmfrKvvQlmJA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-custom-password
      namespace: monitoring
    type: Opaque
