helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: kube-prometheus-stack
    namespace: monitoring
    version: 72.0.1
    valuesFile: values.yaml

resources:
  - grafana-secrets-sealed.yaml
  - tls-cert.yaml