apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-nora-tls-cert
  namespace: monitoring
spec:
  secretName: grafana-nora-tls
  issuerRef:
    name: nora-ca
    kind: ClusterIssuer
  commonName: grafana.nora
  dnsNames:
    - grafana.nora