grafana:
  adminUser: ""
  adminPassword: ""
  admin:
    existingSecret: grafana-custom-password
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      kubernetes.io/ingress.class: "traefik"
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - grafana.nora
    tls:
      - secretName: grafana-nora-tls
        hosts:
          - grafana.nora