image:
  tag: postgresql-latest

umami:
  # debug: "umami:*"
  clientIpHeader: "CF-Connecting-IP"

ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - host: umami.nora
      paths:
        - path: "/"
          pathType: ImplementationSpecific
  tls:
    - secretName: umami-nora-tls
      hosts:
        - umami.nora

postgresql:
  enabled: false

database:
  existingSecret: db-creds
  databaseUrlKey: DATABASE_URL