helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    releaseName: longhorn
    namespace: longhorn-system
    version: 1.8.1
    valuesFile: values.yaml

resources:
  - iscsi.yaml
  - password-secret.sealed.yaml

components:
  - ../../components/tls-ingress

configMapGenerator:
  - name: tls-config
    literals:
      - host=longhorn.nora
      - service=longhorn-frontend
      - port=http
      - pathType=Prefix