preUpgradeChecker:
  jobEnabled: false
persistence:
  defaultClassReplicaCount: 2
defaultSettings:
  storageReservedPercentageForDefaultDisk: 10
  # deletingConfirmationFlag: true      # Enable when uninstalling