helmCharts:
  - name: cert-manager
    repo: oci://quay.io/jetstack/charts
    releaseName: cert-manager
    namespace: cert-manager
    version: v1.19.1
    valuesFile: values.yaml

resources:
  - nora-ca-secret.sealed.yaml
  - issuer.yaml