apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy-deployment
  labels:
    app: ntfy-deployment
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: ntfy-pod
  template:
    metadata:
      labels:
        app: ntfy-pod
    spec:
      containers:
        - name: ntfy 
          image: binwiederhier/ntfy:v2.15.0
          args: ["serve"]
          env:
            - name: TZ
              value: Europe/Warsaw
            - name: NTFY_DEBUG
              value: "false"
            - name: NTFY_LOG_LEVEL
              value: INFO
            - name: NTFY_BASE_URL
              value: http://ntfy.nora 
            - name: NTFY_CACHE_FILE
              value: /var/cache/ntfy/cache.db
            - name: NTFY_AUTH_FILE
              value: /var/lib/ntfy/auth.db
            - name: NTFY_AUTH_DEFAULT_ACCESS
              value: "deny-all"
            - name: NTFY_AUTH_USERS
              value: "myzek:$$2a$$10$$UF5IlcTlI71snSp6lT6JE.07CvrQXH3MOkuJlya5PG2zTT9wAgVCa:admin,backup-script:$$2a$$10$$uWi4POlWRBEzwqrog6q31.hQ6M8EbyTijEdiN4h3OlHYjuAJI3jcu:user"
            - name: NTFY_AUTH_ACCESS
              value: "backup-script:backups:rw"
            - name: NTFY_ENABLE_LOGIN
              value: "true"
            - name: NTFY_REQUIRE_LOGIN
              value: "true"
          ports: 
            - containerPort: 80
              name: http-ntfy
          resources:
            limits:
              memory: 300Mi
              cpu:  200m
            requests:
                  cpu: 150m
                  memory: 150Mi
          volumeMounts:
              - mountPath: /etc/ntfy
                subPath: server.yml
                name: config-volume
              - mountPath: /var/cache/ntfy
                name: cache-volume
              - mountPath: /var/lib/ntfy
                name: db-volume
        - name: nginx
          image: nginx:stable-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: config-volume
          configMap:
            name: server-config
        - name: cache-volume
          persistentVolumeClaim:
            claimName: ntfy-pvc
        - name: db-volume
          persistentVolumeClaim:
            claimName: ntfy-db-pvc
        - name: nginx-config-volume
          configMap:
            name: nginx-config