helmCharts:
  - name: pihole
    repo: https://mojo2600.github.io/pihole-kubernetes/
    releaseName: pihole
    namespace: pihole
    version: 2.30.0
    valuesFile: values.yaml

resources:
  - password-secret-sealed.yaml
  - tailscale-service.yaml
  - tls-cert.yaml