helmCharts:
  - name: pihole
    repo: https://mojo2600.github.io/pihole-kubernetes/
    releaseName: pihole
    namespace: pihole
    version: 2.30.0
    valuesFile: values.yaml

resources:
  - password-secret-sealed.yaml
  - tailscale-service.yaml

components:
  - ../../components/tls-ingress

configMapGenerator:
  - name: tls-config
    literals:
      - host=pihole.nora
      - service=pihole-web
      - port=http
      - pathType=ImplementationSpecific